name: mi_tarea03_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^2.7.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/animations/
  fonts: 
      - family: CascadiaCode
        fonts:
          - asset: assets/fonts/CascadiaCode-Regular.ttf
